/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println(new Calculate().sum_order(2, 3));
    System.out.println(new Calculate().sum_order(1, 10));
    System.out.println(new Calculate().sum_order(1, 10, "odd"));
  }
}
